### ISSUE TITLE
2.0 docs: "Minimal example of tab-based navigation" yields error

### ISSUE THREAD

**Issue by tassock** [react-navigation/react-navigation.github.io#129]
I'm trying to figure out how to set up a bottom tab bar nav on 2.0.0-rc.2. This 2.0 doc on the subject uses the new createBottomTabNavigator API method: 

https://github.com/react-navigation/react-navigation.github.io/blob/2.x/docs/tab-based-navigation.md#minimal-example-of-tab-based-navigation

When I copy that verbatim into my App.js, I see the tab navigation as expected. However, when I select the other tab I get the error "navigation.navigate is not a function". See screen for trace. I'm guessing that this is an error in the docs and not the release candidate. I poked around in the 2.0 source for about an hour trying to figure out the right way to do this, but came up empty handed. If someone can explain how tab navigation is supposed to work in 2.0, I can open a PR to fix the docs. 

Thanks!

Peter

![screen shot 2018-04-11 at 4 51 35 pm](https://user-images.githubusercontent.com/74180/38649162-e6379ada-3da9-11e8-9b8a-b2918ca862f0.png)

**Comment by tassock** [comment]
This appears to be fixed in 2.0.0-rc.5

**Comment by brentvatne** [comment]
sorry about that!
